export const residents = [
  {
    id: "siyeon",
    name: "한시연",
    gender: "여성",
    pillars: ["경진", "계미", "임오", "경자"],
    role: "달빛 우체부",
    place: "달빛 우체국",
    quote: "말하지 않은 마음도, 무사히 도착하도록.",
    story:
      "한낮의 뜨거운 마을에 밤의 편지를 배달한다. 물의 유연함과 금의 정리하는 이미지로 만든 기록자. 누구의 편지를 먼저 열어 볼지는 언제나 비밀이다.",
    color: "#6599b4",
    hat: "moon",
  },
  {
    id: "jaehwan",
    name: "김재환",
    gender: "남성",
    pillars: ["을유", "임오", "정해", null],
    role: "별불 등대지기",
    place: "별불 등대",
    quote: "네가 길을 잃으면, 내가 불을 켤게.",
    story:
      "작은 불을 오래 지키는 등대지기. 여름의 정화와 해수의 대비를, 밝게 웃으면서도 혼자 생각하는 밤이 있는 캐릭터로 옮겼다.",
    color: "#e09c75",
    hat: "lamp",
  },
  {
    id: "sihyeon",
    name: "안시현",
    gender: "여성",
    pillars: ["을유", "무자", "무진", "을묘"],
    role: "겨울 정원사",
    place: "새싹 온실",
    quote: "천천히 자라는 것도, 분명 자라고 있어.",
    story:
      "겨울 흙 위에 작은 온실을 세운다. 무토의 단단한 이미지와 목의 새싹을 엮어, 친구들의 새로운 시작을 조용히 돕는 정원사로 만들었다.",
    color: "#a4b587",
    hat: "leaf",
  },
  {
    id: "yeonjae",
    name: "송연재",
    gender: "남성",
    pillars: ["임오", "병오", "갑술", null],
    role: "햇살 모험가",
    place: "햇살 전망대",
    quote: "재밌겠다. 우리 일단 가 볼까?",
    story:
      "뜨거운 계절을 향해 가지를 뻗는 나무. 갑목과 겹친 오화의 이미지를 길을 먼저 발견하는 모험가로 표현했다. 물 한 병을 챙겨 주는 친구가 소중하다.",
    color: "#dfac50",
    hat: "adventure",
  },
  {
    id: "kangmin",
    name: "하강민",
    gender: "남성",
    pillars: ["계미", "임술", "경신", "신사"],
    role: "은빛 대장장이",
    place: "은빛 공방",
    quote: "네가 상상하면, 내가 만들어 볼게.",
    story:
      "금속의 결을 읽고 고장 난 나침반을 고친다. 경금과 신금의 이미지를 도구와 작업복으로 풀었다. 투박한 선물에도 오래 고른 마음이 담겨 있다.",
    color: "#8da7a3",
    hat: "forge",
  },
  {
    id: "kanghyeon",
    name: "김강현",
    gender: "남성",
    pillars: ["신사", "무술", "무진", null],
    role: "산책길 건축가",
    place: "돌담 설계소",
    quote: "돌아올 자리는 내가 만들어 둘게.",
    story:
      "마을의 돌담과 벤치를 만드는 건축가. 무토와 진술의 대비를 오래 버티는 구조와 새로 고치고 싶은 마음이라는 두 이미지로 해석한 캐릭터다.",
    color: "#ba9b78",
    hat: "builder",
  },
  {
    id: "hyeonjeong",
    name: "현정",
    gender: "여성",
    pillars: ["임오", "무신", "경술", "임오"],
    role: "바람길 항해사",
    place: "바람 선착장",
    quote: "바람이 바뀌면, 돛을 바꾸면 되지.",
    story:
      "금과 수의 이미지를 나침반과 항해 지도로 옮겼다. 낯선 길에서 지도를 펼치는 항해사. 두 개의 오화는 배의 작은 붉은 깃발이 되었다.",
    color: "#7faab1",
    hat: "sailor",
  },
  {
    id: "seyeong",
    name: "세영",
    gender: "여성",
    pillars: ["임오", "계묘", "기축", null],
    role: "봄비 찻집 주인",
    place: "봄비 찻집",
    quote: "아무 말 안 해도 돼. 차는 따뜻해.",
    story:
      "봄날의 흙과 물을 찻잔과 작은 화단으로 바꿨다. 각자의 속도로 머물 수 있는 찻집을 연다. 말보다 기다림으로 이야기를 이어 가는 역할이다.",
    color: "#b6a17c",
    hat: "tea",
  },
  {
    id: "inha",
    name: "인하",
    gender: "남성",
    pillars: ["계미", "갑인", "신미", null],
    role: "꽃잎 보석상",
    place: "꽃결 보석점",
    quote: "작은 차이가, 특별함을 만들잖아.",
    story:
      "봄 숲 속의 신금을 꽃잎 같은 보석으로 표현했다. 작고 반짝이는 물건을 찾아 친구에게 맞는 선물을 만든다. 가게 서랍마다 서로 다른 이야기가 있다.",
    color: "#b59abc",
    hat: "gem",
  },
  {
    id: "garyeong",
    name: "가령",
    gender: "여성",
    pillars: ["임오", "임자", "병자", null],
    role: "새벽빛 화가",
    place: "새벽 아틀리에",
    quote: "가장 어두운 파랑에도 빛은 있어.",
    story:
      "겨울 물 위에 떠오르는 병화의 풍경에서 태어난 화가. 파란 화면 한가운데 따뜻한 색을 남긴다. 조용한 밤마다 마을 사람들의 새로운 모습을 그린다.",
    color: "#dc9390",
    hat: "artist",
  },
  {
    id: "jinha",
    name: "진하",
    gender: "남성",
    pillars: ["임오", "무신", "임술", null],
    role: "구름 수집가",
    place: "구름 도서관",
    quote: "그 이야기, 조금 더 들려줄래?",
    story:
      "가을의 큰 물을 구름과 책장으로 옮겼다. 마을의 이야기를 모으고 새로운 결말을 상상한다. 같은 사건도 다른 창문에서 보면 달라진다는 걸 좋아한다.",
    color: "#8e9cbd",
    hat: "cloud",
  },
  {
    id: "doyun",
    name: "도윤",
    gender: "남성",
    pillars: ["계미", "경신", "계유", null],
    role: "이슬 연금술사",
    place: "이슬 연구실",
    quote: "아주 작은 발견이, 내일을 바꿀지도.",
    story:
      "금과 계수의 이미지를 유리병 속 이슬로 표현했다. 새벽에 모은 반짝임으로 마을의 조명을 만든다. 작은 실험의 결과를 친구들과 나누는 연구자다.",
    color: "#84b9ad",
    hat: "wizard",
  },
];
export const elements = ["목", "화", "토", "금", "수"];
export const elementColors = [
  "#7aab7d",
  "#df8a70",
  "#c2a366",
  "#9ba8b3",
  "#709bbd",
];
export const archetypes = {
  갑: {
    nature: "큰 나무",
    symbol: "🌳",
    text: "위로 뻗는 줄기와 넓은 가지",
    motif: "등 뒤의 작은 나무",
  },
  을: {
    nature: "덩굴과 꽃",
    symbol: "🌿",
    text: "유연하게 이어지는 줄기",
    motif: "몸을 감싸는 잎사귀",
  },
  병: {
    nature: "태양과 큰 불",
    symbol: "☀️",
    text: "주변을 넓게 비추는 빛",
    motif: "등 뒤의 태양 원반",
  },
  정: {
    nature: "작은 촛불",
    symbol: "🕯️",
    text: "가까운 곳을 오래 밝히는 불",
    motif: "곁을 따라다니는 촛불",
  },
  무: {
    nature: "큰 산",
    symbol: "⛰️",
    text: "넓은 바탕과 단단한 능선",
    motif: "발밑의 작은 산봉우리",
  },
  기: {
    nature: "밭과 정원",
    symbol: "🌱",
    text: "씨앗을 품고 기르는 흙",
    motif: "새싹이 자라는 작은 밭",
  },
  경: {
    nature: "바위와 원석",
    symbol: "🪨",
    text: "형태를 잡아 가는 단단한 금속",
    motif: "곁에 떠 있는 은빛 원석",
  },
  신: {
    nature: "보석",
    symbol: "💎",
    text: "섬세하게 다듬어진 반짝임",
    motif: "빛나는 보석 조각",
  },
  임: {
    nature: "큰 바다",
    symbol: "🌊",
    text: "넓게 흐르고 많은 것을 품는 물",
    motif: "몸 주위를 감싸는 바다 물결",
  },
  계: {
    nature: "시냇물과 이슬",
    symbol: "💧",
    text: "작고 섬세하게 이어지는 물",
    motif: "발밑의 시냇물과 이슬",
  },
};
